### ISSUE TITLE
Unable to put EdgeOS into Configure Mode

### ISSUE THREAD

**Issue by Gervarez** [ytti/oxidized-script#26]
I'm having issues with making configuration changes to Ubiquiti Edge Routers using oxs. I'm able to run commands on the Edge routers, but whenever I try to put it into configuration mode I get the following errors:

```
/var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:138:in `sleep': execution expired (Timeout::Error)
	from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:138:in `block (2 levels) in expect'
	from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:98:in `ev_preprocess'
	from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/event_loop.rb:27:in `process'
	from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:216:in `process'
	from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `block in loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /var/lib/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:178:in `loop'
	from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:137:in `block in expect'
	from /usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
	from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:136:in `expect'
	from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:129:in `cmd_shell'
	from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/input/ssh.rb:74:in `cmd'
	from /var/lib/gems/2.3.0/gems/oxidized-0.24.0/lib/oxidized/model/model.rb:103:in `cmd'
	from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/lib/oxidized/script/script.rb:23:in `cmd'
	from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/lib/oxidized/script/cli.rb:41:in `run'
	from /var/lib/gems/2.3.0/gems/oxidized-script-0.5.1/bin/oxs:5:in `<top (required)>'
	from /usr/local/bin/oxs:23:in `load'
	from /usr/local/bin/oxs:23:in `<main>' 
```

An example of how you get into configure mode on EdgeOS:

```
admin@hostname:~$ configure
[edit]
admin@hostname#
```

**Comment by laf** [comment]
You should show what you are sending across.
