### ISSUE TITLE
oxs command not found

### ISSUE THREAD

**Issue by dcoble17** [ytti/oxidized-script#30]
I'm a newb to Oxidized and Linux for that matter.  I have oxidized running on Centos with no problem but want to use oxs and I can't run it.  I have installed it but i get oxs command not found when running with sudo, without sudo I get the below.

[oxidized@oxidized1 /]$ oxs
/usr/share/rubygems/rubygems/dependency.rb:296:in `to_specs': Could not find 'oxidized-script' (>= 0) among 37 total gem(s) (Gem::LoadError)
        from /usr/share/rubygems/rubygems/dependency.rb:307:in `to_spec'
        from /usr/share/rubygems/rubygems/core_ext/kernel_gem.rb:47:in `gem'
        from /usr/local/bin/oxs:22:in `<main>'

It installed correctly,
[oxidized@oxidized1 /]$ sudo gem install oxidized-script
Successfully installed oxidized-script-0.6.0
Parsing documentation for oxidized-script-0.6.0
1 gem installed

But if i search for oxidized-script it doesn't find anything.

**Comment by dcoble17** [comment]
Sorry i found the issue. Rights issue on cli.rb was for root only.
