### ISSUE TITLE
cannot load such file -- oxidized/script/cli

### ISSUE THREAD

**Issue by Moonbeam4520** [ytti/oxidized-script#33]
i just installed oxs with `gem install oxidized-script` as root, 
when I launch oxs as oxidized user, it gives this error
```
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- oxidized/script/cli (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /var/lib/gems/2.1.0/gems/oxidized-script-0.6.0/bin/oxs:4:in `<top (required)>'
	from /usr/local/bin/oxs:23:in `load'
	from /usr/local/bin/oxs:23:in `<main>'
```

**Comment by sorano** [comment]
I am experiencing the same thing:
```
oxidized@nms:~/.config/oxidized$ oxs
Traceback (most recent call last):
        5: from /usr/local/bin/oxs:23:in `<main>'
        4: from /usr/local/bin/oxs:23:in `load'
        3: from /var/lib/gems/2.5.0/gems/oxidized-script-0.6.0/bin/oxs:4:in `<top (required)>'
        2: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        1: from /usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/usr/local/lib/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- oxidized/script/cli (LoadError)
```

I did this as a workaround, might not be the prettiest solution but at least it works for now:
sudo visudo
oxidized ALL=(ALL) NOPASSWD: /usr/local/bin/oxs

```
oxidized@nms:~/.config/oxidized$ sudo oxs
no host given
```

**Comment by davama** [comment]
Same...

```
/usr/local/rvm/gems/ruby-2.3.8/bin/oxs -u $USER -p $loginpass -m procurve host 'sh ll i r' 
/usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- oxidized/script/cli (LoadError)
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	from /usr/local/rvm/gems/ruby-2.3.8/gems/oxidized-script-0.6.0/bin/oxs:4:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.8/bin/oxs:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.8/bin/oxs:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.8/bin/ruby_executable_hooks:24:in `<main>'

```

**Comment by DoctorHurt** [comment]
Same problem here. I found a file cli.rb that was only executable by root. 
To fix, I changed it to world-executable and I can now run oxs with no problems as the oxidized user.

```
root@netnms01:/var/lib/gems/2.5.0/gems/oxidized-script-0.6.0/lib/oxidized/script# ll
drwxr-xr-x 3 root root 4096 Aug 14 15:51 ./
drwxr-xr-x 3 root root 4096 Aug 14 15:51 ../
-rwx------ 1 root root 6210 Aug 14 15:51 cli.rb*
-rw-r--r-- 1 root root   95 Aug 14 15:51 command.rb
drwxr-xr-x 2 root root 4096 Aug 14 15:51 commands/
-rw-r--r-- 1 root root 3783 Aug 14 15:51 script.rb
root@netnms01:/var/lib/gems/2.5.0/gems/oxidized-script-0.6.0/lib/oxidized/script# chmod 755 cli.rb
```

**Comment by davama** [comment]
>Same problem here. I found a file cli.rb that was only executable by root.
To fix, I changed it to world-executable and I can now run oxs with no problems as the oxidized user.

Interesting, will have to try

**Comment by michelbragaguimaraes** [comment]
> Same problem here. I found a file cli.rb that was only executable by root. To fix, I changed it to world-executable and I can now run oxs with no problems as the oxidized user.
> 
> ```
> root@netnms01:/var/lib/gems/2.5.0/gems/oxidized-script-0.6.0/lib/oxidized/script# ll
> drwxr-xr-x 3 root root 4096 Aug 14 15:51 ./
> drwxr-xr-x 3 root root 4096 Aug 14 15:51 ../
> -rwx------ 1 root root 6210 Aug 14 15:51 cli.rb*
> -rw-r--r-- 1 root root   95 Aug 14 15:51 command.rb
> drwxr-xr-x 2 root root 4096 Aug 14 15:51 commands/
> -rw-r--r-- 1 root root 3783 Aug 14 15:51 script.rb
> root@netnms01:/var/lib/gems/2.5.0/gems/oxidized-script-0.6.0/lib/oxidized/script# chmod 755 cli.rb
> ```

That worked for me.

On my case it was under: /usr/local/rvm/gems/ruby-2.6.0/gems/oxidized-script-0.6.0/lib/oxidized/script/

**Comment by nickhilliard** [comment]
fixed in 6f26418.
