### ISSUE TITLE
Newer version of oxidized-script gem

### ISSUE THREAD

**Issue by codeout** [ytti/oxidized-script#43]
Hi @ytti, do you have any plan to publish newer version as gem?

oxidized-script `0.6.0` doesn't work along with oxidized `0.28` due to version conflict of "slop" gem.

Thanks,

### oxidized-script 0.6.0
https://github.com/ytti/oxidized-script/blob/a86cebbfc0b5c1996ec65c2da98e70df9e00b846/oxidized-script.gemspec#L16-L17

```ruby
  s.add_runtime_dependency 'oxidized', '~> 0.25'  # covers 0.28.0
  s.add_runtime_dependency 'slop',     '~> 3.5'   # but this conflicts with 4.6
```

### oxidized 0.28.0
https://github.com/ytti/oxidized/blob/835384c6bb3a02896d05c73a1476c054b0856965/oxidized.gemspec#L27

```ruby
s.add_runtime_dependency 'slop',    '~> 4.6'
```

**Comment by ghost** [comment]
@ytti, can you give me permissions in the github project and on rubygems? then I will publish a new gem

**Comment by ytti** [comment]
@mortzu you actually had it on rubygems, I removed them earlier today for three independent reasons, inactivity, another contributor rolled gem for oxidized yesterday and lack of MFA. 

I will give @aschaber1 right of first refusal, on thesis that more cooks isn't better for pushing out releases. Should he refuse, I'll set you up.

**Comment by ghost** [comment]
yeah. thats fine for me

**Comment by aschaber1** [comment]
I'm happy either way. I can do the release today, or @mortzu can do it.
I'll propose a GitHub Action on the weekend anyway, that will release ruby gems automatically on merge on master. Then this becomes a non-issue.

**Comment by joschi99** [comment]
oxidized version 0.29 is now available

**Comment by ghost** [comment]
> I'm happy either way. I can do the release today, or @mortzu can do it. I'll propose a GitHub Action on the weekend anyway, that will release ruby gems automatically on merge on master. Then this becomes a non-issue.

any news?

**Comment by aschaber1** [comment]
https://github.com/ytti/oxidized/pull/2754

My friend created some pipelines which might help us out :)

**Comment by cjwbath** [comment]
+1 on finishing this off - just did a new gem install and have ended up with:
- oxidized 0.29.1 polling configs, working fine
- oxidized-script 0.6.0, using libraries from oxidized 0.26.3 pulled in as dependency, not able to connect to anything via SSH:
```
oxidized@oxidized:~$ oxs -d -v test.thing 'show run'
unable to connect
/var/lib/gems/3.1.0/gems/oxidized-script-0.6.0/lib/oxidized/script/script.rb:113:in `connect': unable to connect (Oxidized::Script::NoConnection)
        from /var/lib/gems/3.1.0/gems/oxidized-script-0.6.0/lib/oxidized/script/script.rb:92:in `initialize'
        from /var/lib/gems/3.1.0/gems/oxidized-script-0.6.0/lib/oxidized/script/cli.rb:122:in `new'
        from /var/lib/gems/3.1.0/gems/oxidized-script-0.6.0/lib/oxidized/script/cli.rb:122:in `connect'
        from /var/lib/gems/3.1.0/gems/oxidized-script-0.6.0/lib/oxidized/script/cli.rb:37:in `run'
        from /var/lib/gems/3.1.0/gems/oxidized-script-0.6.0/bin/oxs:5:in `<top (required)>'
        from /usr/local/bin/oxs:25:in `load'
        from /usr/local/bin/oxs:25:in `<main>'
```
Trying to debug that any further is really hard without hacking around in the code (-d and -v flags don't seem to have helped) and I don't want to do that on an old version if the new version is apparently working.

**Comment by ahab77** [comment]
we have the same problem. With oxidized 0.29.1 the connection works, with oxs or oxidized-script 0.6.0 no connection can be established. Same error as with cjwbath

**Comment by Vladyslav78956785786576** [comment]
Up.

**Comment by nickhilliard** [comment]
this should be fixed in [0.70.0](https://github.com/ytti/oxidized-script/releases/tag/0.70.0)

**Comment by codeout** [comment]
Thanks nickhilliard, oxidized-script 0.7.0 works fine with oxidized 0.30.1.

```
a $ bundle list 
Gems included by the bundle:
  * asetus (0.4.0)
  * bcrypt_pbkdf (1.1.1)
  * date (3.4.1)
  * ed25519 (1.3.0)
  * net-ftp (0.3.8)
  * net-protocol (0.2.2)
  * net-scp (4.1.0)
  * net-ssh (7.3.0)
  * net-telnet (0.2.0)
  * oxidized (0.30.1)
  * oxidized-script (0.7.0)
  * psych (3.3.4)
  * rugged (1.9.0)
  * slop (4.10.1)
  * time (0.4.1)
  * timeout (0.4.3)
Use `bundle info` to print more detailed information about a gem

a $ bundle exec oxs -m junos -u me 10.0.0.1 "show system uptime"
Current time: 2025-01-23 13:58:02 JST
...
```
