### ISSUE TITLE
OXS SSH unable to connect (Oxidized::Script::NoConnection)

### ISSUE THREAD

**Issue by michelbragaguimaraes** [ytti/oxidized-script#47]
# Information about my configuration:

oxidized (0.29.1, 0.26.3)
oxidized-script (0.6.0)
oxidized-web (0.13.1)
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
gem version - 3.3.5
Ubuntu 22.04

Oxidized configuration:

`---
interval: 3600
use_syslog: true
log: /home/oxidized/.config/oxidized/logs/oxidized.log
debug: true
threads: 40
timeout: 20
retries: 0
prompt: !ruby/regexp /^([\w.@-]+[#>]\s?)$/

crash:
  directory: "/home/oxidized/.config/oxidized/crashes"
  hostnames: false

#Enable web interface:
rest: 127.0.0.1:8888
pid: "/home/oxidized/.config/oxidized/pid"

#Set local history size to 2 files:
stats:
  history_size: 2

#Custom settings for different groups:
groups:
  ios:
    username: user
    password: "XXXXXXXXX"
  asa:
    username: user
    password: "XXXXXXXXX"
    vars:
      enable: "XXXXXXXXX"
  ciscowlc:
    username: user
    password: "XXXXXXXXX"
  fabos:
    username: user
    password: "XXXXXXXXX"
  lab:
    username: user
    password: "XXXXXXXXX"
  paloalto:
    username: user
    password: "XXXXXXXXX"

#Settings for device models:
#models:
###pfsense:
#####username: user4
#####password: pass4
#####ssh_keys: "/home/oxidized/.config/oxidized/ssh/id_rsa"

#Settings for data input:
input:
  debug: true
  default: ssh
  ssh:
    secure: false

#Settings for default data output:
output:
  debug: true
  default: git
  git:
      single_repo: true
      user: xxxxxxxxx
      email: xxxxxxxx@xxxxxxxxxx
      repo: "/home/oxidized/.config/oxidized/Network/config.git"

#Settings for data source:
source:
  default: http
  http:
    url: https://127.0.0.1/api/v0/oxidized
    scheme: https
    secure: false
    delimiter: !ruby/regexp /:/
    map:
      name: hostname
      model: os
      group: group
    headers:
      X-Auth-Token: 'tokentokentokentokentokentoken'
#Model maps to common names:
model_map:
  juniper: junos
  cisco: ios
  ciscowlc: aireos
  lab: ios
  fabos: fabricos
  asa: asa
  paloalto: panos

hooks:
  push_to_remote:
    type: githubrepo
    events: [post_store]
    remote_repo: "git@ssh.dev.azure.com:v3/xxxxxxxxx/xxxxxxx/librenms"
    publickey: /home/oxidized/.ssh/id_rsa.pub
    privatekey: /home/oxidized/.ssh/id_rsa`

# Problem I am having

The librenms + oxidized integration works without any problem. Everything is being backed up, and I have a local copy and a copy on azure git. Beautiful!

My problem is when I try to use oxs.

When the device has telnet enabled, with this command I can pull the config: oxs <device IP or name> 'sh run'

But I got the following error every time I try to do the same command on devices that has only ssh enable or when I change the configuration only to use ssh:

`/var/lib/gems/3.0.0/gems/oxidized-script-0.6.0/lib/oxidized/script/script.rb:113:in `connect': unable to connect (Oxidized::Script::NoConnection)
        from /var/lib/gems/3.0.0/gems/oxidized-script-0.6.0/lib/oxidized/script/script.rb:92:in `initialize'
        from /var/lib/gems/3.0.0/gems/oxidized-script-0.6.0/lib/oxidized/script/cli.rb:122:in `new'
        from /var/lib/gems/3.0.0/gems/oxidized-script-0.6.0/lib/oxidized/script/cli.rb:122:in `connect'
        from /var/lib/gems/3.0.0/gems/oxidized-script-0.6.0/lib/oxidized/script/cli.rb:37:in `run'
        from /var/lib/gems/3.0.0/gems/oxidized-script-0.6.0/bin/oxs:5:in `<top (required)>'
        from /usr/local/bin/oxs:25:in `load'
        from /usr/local/bin/oxs:25:in `<main>'`

And to be fair, I want to make ssh work because is way more secure.

Does anyone have a similar problem? Is there a fix for it?

Thank you

**Comment by shoeb17** [comment]
I am having the exact same issue, any help or guidance how we can fix this will be much appreciated.

**Comment by rchen14b** [comment]
For people having this issue:

I had same problem, after debugging, looks like the problem is the version of the slop dependency is mismatching with what installed from oxidized.

To workaround this:
1. Uninstall current oxidized script and also the oxidized 0.26 it installed.
2. git clone the current master branch.
3. under the root folder, do "gem build" it will creates FILENAME..gem file to install.
4. do gem install FILENAME.gem 

That should fix the issue until there is a new oxidized-script version release.

**Comment by nickhilliard** [comment]
fixed in [0.70.0](https://github.com/ytti/oxidized-script/releases/tag/0.70.0)
