### ISSUE TITLE
Please issue release 0.6.1

### ISSUE THREAD

**Issue by nickhilliard** [ytti/oxidized-script#49]
Any chance of tagging the current master as 0.6.1 and uploading it to the gem repo?

`oxidized` requires slop4, but `oxidized-script` 0.6.0 which depends on slop 3, which raises the following exception when you attempt to start `oxs`:

```
$ oxs
/usr/local/lib/ruby/site_ruby/3.2/rubygems/specification.rb:1474:in `block in activate_dependencies': can't satisfy 'slop (~> 3.5)', already activated 'slop-4.10.1' (Gem::LoadError)
	from /usr/local/lib/ruby/site_ruby/3.2/rubygems/specification.rb:1466:in `each'
	from /usr/local/lib/ruby/site_ruby/3.2/rubygems/specification.rb:1466:in `activate_dependencies'
	from /usr/local/lib/ruby/site_ruby/3.2/rubygems/specification.rb:1448:in `activate'
	from /usr/local/lib/ruby/site_ruby/3.2/rubygems.rb:280:in `block in activate_bin_path'
	from /usr/local/lib/ruby/site_ruby/3.2/rubygems.rb:279:in `synchronize'
	from /usr/local/lib/ruby/site_ruby/3.2/rubygems.rb:279:in `activate_bin_path'
	from /usr/local/bin/oxs:25:in `<main>'
$
```

**Comment by candlerb** [comment]
I think it needs further updating anyway.

The latest release (0.6.0, Dec 2018) and depends on `'oxidized', '~> 0.25'`. There have been a few commits since then, with one in Dec 2021  to depend on `'oxidized', '~> 0.28'` - but current is 0.30.

When I try to install on Ubuntu 24.04, I actually get oxidized-0.26.3 (I can't work out why that version in particular), and it fails because of other ancient dependencies:

```
# gem install -N oxidized-script
Fetching net-ssh-5.2.0.gem
Fetching oxidized-script-0.6.0.gem
Fetching oxidized-0.26.3.gem
Fetching slop-3.6.0.gem
Fetching rugged-0.99.0.gem
Fetching net-telnet-0.1.1.gem
Successfully installed slop-3.6.0
Building native extensions. This could take a while...
ERROR:  Error installing oxidized-script:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.2.0/gems/rugged-0.99.0/ext/rugged
/usr/bin/ruby3.2 -I/usr/lib/ruby/vendor_ruby extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)3.2
	--with-sha1dc
	--without-sha1dc
	--use-system-libraries
extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
	from extconf.rb:100:in `chdir'
	from extconf.rb:100:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.2.0/gems/rugged-0.99.0 for inspection.
Results logged to /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/gem_make.out
```

This bug - using obsolete `Dir.exists?` when it should be `Dir.exist?` - was fixed a long time ago in rugged (commit 40be15df in Jan 2022), and the main oxidized gem is fine (it depends on `rugged ~> 1.6`)

Comparing with the dependences of the main oxidized gem (0.30.1):

```
gem install -N oxidized
Fetching net-scp-4.0.0.gem
Fetching rugged-1.7.2.gem
Fetching net-ssh-7.2.3.gem
Fetching slop-4.10.1.gem
Fetching psych-3.3.4.gem
Fetching ed25519-1.3.0.gem
Fetching bcrypt_pbkdf-1.1.0.gem
Fetching oxidized-0.30.1.gem
Fetching asetus-0.4.0.gem
```
