### ISSUE TITLE
Help with installing oxidized-script [Failed to build gem native extension]

### ISSUE THREAD

**Issue by Harrifresh** [ytti/oxidized-script#50]
Hi all,

I saw someone else posted this exact problem on the top level Oxidized page but they were directed here instead. I couldn't find another issue from the same poster so I've created my own. https://github.com/ytti/oxidized/issues/3200

I've setup an ubuntu 24.04 server to run oxidized, getting this error when attempting to install the oxidized-script gem:

```
Building native extensions. This could take a while...
ERROR:  Error installing oxidized-script:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.2.0/gems/rugged-0.99.0/ext/rugged
/usr/bin/ruby3.2 -I/usr/lib/ruby/vendor_ruby extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)3.2
        --with-sha1dc
        --without-sha1dc
        --use-system-libraries
extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
        from extconf.rb:100:in `chdir'
        from extconf.rb:100:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.2.0/gems/rugged-0.99.0 for inspection.
Results logged to /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/gem_make.out
```

Looking at the mkmf.log file shows no errors:

```
find_executable: checking for gmake... -------------------- yes

--------------------

find_executable: checking for cmake... -------------------- yes

--------------------

find_executable: checking for pkg-config... -------------------- yes

--------------------
```

The original poster suggested there could be a typo in the script where it should be "exist" but it's written as "exists". Not sure if that is the problem but the error message points in that direction.

Is anyone able to assist please? 

Thanks in advance
Harri

**Comment by ylmrx** [comment]
hitting the same wall here, and it's quite inconvenient : latest `oxidized-web` rely on ruby3.2, `oxidized-script` require ruby3.0, you can't have both.

building my container with ubuntu-jammy (carries ruby3.0) and downgrading oxidized-web to `0.13.1`.

is ubuntu-noble a hard requirement for you ?

**Comment by bram-pangestu** [comment]
i also face the same issue. Waiting for update/good news

**Comment by robertcheramy** [comment]
If no one steps into maintaining oxidized-script, I'm sorry to say that the chances for good news are near zero.
I've stepped into maintaining oxidized and oxidized-web and there is more work than I can handle.

[Ruby 3.0 is end of life](https://www.ruby-lang.org/en/downloads/branches/) and both oxidized and oxidized-web require ruby 3.1 as a minimal requirement.

**Comment by scarygary** [comment]
I'm using Oxidized on at least three different sites and would love to help. I am however no Ruby coder, so I wouldn't know the first thing about fixing the error.

**Comment by crawc** [comment]
Same issue with Ubuntu 24.04.1 LTS.

**Comment by nickhilliard** [comment]
Stale dependency problem. Fixed in https://github.com/ytti/oxidized-script/releases/tag/0.70.0
