### ISSUE TITLE
oxidized-script fails to install on ubuntu 24.04 (ruby 3.2)

### ISSUE THREAD

**Issue by anubisg1** [ytti/oxidized-script#51]
as per title

```
root@OXIDIZED:/home/azureuser# gem install oxidized-script
Building native extensions. This could take a while...
ERROR:  Error installing oxidized-script:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/3.2.0/gems/rugged-0.99.0/ext/rugged
/usr/bin/ruby3.2 -I/usr/lib/ruby/vendor_ruby extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)3.2
        --with-sha1dc
        --without-sha1dc
        --use-system-libraries
extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
        from extconf.rb:100:in `chdir'
        from extconf.rb:100:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/3.2.0/gems/rugged-0.99.0 for inspection.
Results logged to /var/lib/gems/3.2.0/extensions/x86_64-linux-gnu/3.2.0/rugged-0.99.0/gem_make.out
```

this seems a problem with a dependency, specifically rugged

**Comment by PatrickstarWritesCode** [comment]
Are there any workarounds?

**Comment by charlesthorsen** [comment]
I'm attempting to figure this out - maybe remove ruby 3.2 and install 3.1? I'm a linux noob so please don't flame me.

**Comment by charlesthorsen** [comment]
i was able to install ruby 3.1.x 
[by following this and making sure i installed 3.1.2 ](https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-20-04)
`:~$ ruby -v`
`ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]`

and cleaned up any instance of Ruby3.2.0 my removing anything related to ruby3.2.0

`remove ruby 3.2.0`
`rm -Rf /usr/lib/ruby`
`rm -Rf /var/lib/gems/3.2.0`
`rm -Rf /usr/share/rubygems-integration/`
`rm -Rf /usr/share/ri/3.2.0/`
`rm -Rf /usr/include/ruby-3.2.0/`
`rm -Rf /usr/bin/ruby3.2`
`rm -Rf /etc/apparmor.d/abstractions/ruby`
`rm -Rf /home/<username>/.local/share/gem/ruby`
`rm -Rf /home/<username>/.local/share/gem/ruby/`
`rm -Rf /usr/bin/ruby3.2`
`rm -Rf /usr/include/ruby-3.2.0`
`rm -Rf /usr/include/x86_64-linux-gnu/ruby-3.2.0`

after all that clean up i ran the 

`gem install oxidized-script oxidized-web` 

and still got the same error

**Comment by charlesthorsen** [comment]
@:~$ gem env home
/home/<username>/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0

**Comment by charlesthorsen** [comment]
removing the ruby and ruby-dev from the command

'apt-get install libsqlite3-dev libssl-dev pkg-config cmake libssh2-1-dev libicu-dev zlib1g-dev g++ libyaml-dev'

requires the ruby and ruby-dev - unable to be specific about which version to install.

no good.

**Comment by ssv1907** [comment]
And what about Docker container? Does it work?

**Comment by anubisg1** [comment]
Containers have all dependencies included, it won't touch containers unless
you are building it using Ubuntu 22.04 as a base container build

**Comment by ssv1907** [comment]
On Debian 12.8 I installed everything without problems via apt, there are ruby 3.1 in the repo

**Comment by charlesthorsen** [comment]
awesome good to know - thank you your response
________________________________

**Comment by nickhilliard** [comment]
ubuntu 24.04 confirmed working with [0.70.0](https://github.com/ytti/oxidized-script/releases/tag/0.70.0)
